name: Flutter Web Auto Deploy

on:
  push:
    branches:
      - main  # branch ที่ push จะ trigger workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app   # Flutter project อยู่ในโฟลเดอร์ app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # ใช้ token ของ Actions สำหรับ Public repo
          publish_dir: app/build/web
          publish_branch: gh-pages
