name: Flutter Web Deploy

on:
  push:
    branches:
      - main   # แก้เป็น branch ที่คุณใช้จริง เช่น master หรือ develop

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app   # << Flutter project อยู่ในโฟลเดอร์ app

    steps:
      # ดึง source code
      - uses: actions/checkout@v3

      # ติดตั้ง Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # build flutter web
      - run: flutter build web --release

      # deploy ไป GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/build/web   # output หลัง build
